@startuml QuartaColoniaQuiz

class Dice
class Player
class Board
class Square

Board o-R- Square
Board -L- Player

Player -- Dice

Square o-- Event

PlusEvent --|> Event
MinusEvent --|> Event
Quiz --|> Event

Dice -- Board





@enduml